# Generated by Django 3.2.12 on 2022-02-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_tips'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tips',
        ),
    ]
